import { test, expect } from '@playwright/test';
import { loginAs, getEntitiesBySubtype, getMetadata } from '../helpers/elgg';

test.describe('hypePlaces create flow', () => {
  test('create page renders the edit form for logged-in user', async ({ page }) => {
    await loginAs(page, 'testuser');
    const response = await page.goto('/places/create');
    expect(response?.status() ?? 0).toBeLessThan(500);

    const form = page.locator('form[action*="action/places/edit"], form:has(input[name="title"])').first();
    await expect(form).toBeVisible();
    await expect(page.locator('input[name="title"]')).toBeVisible();
  });

  test('submitting form creates a Place entity with address metadata', async ({ page }) => {
    await loginAs(page, 'testuser');
    await page.goto('/places/create');

    const uniqueTitle = 'Playwright Place ' + Date.now();

    await page.fill('input[name="title"]', uniqueTitle);
    await page.fill('textarea[name="description"]', 'Generated by Playwright test');

    // Address fields (nested under address[...])
    await page.fill('input[name="address[street_address]"]', '100 Test Rd');
    await page.fill('input[name="address[locality]"]', 'Testville');
    await page.fill('input[name="address[postal_code]"]', '99999');
    // Country — may be a select or text input
    const countryInput = page.locator('input[name="address[country]"]').first();
    if (await countryInput.count()) {
      await countryInput.fill('Testland');
    }

    await page.click('button[type="submit"], input[type="submit"]');

    // Give Elgg a moment to redirect after save
    await page.waitForLoadState('networkidle');

    // Assert DB: a new hjplace entity exists with this title
    const entities = await getEntitiesBySubtype('hjplace');
    const created = entities.find((e: any) => {
      // title is stored as metadata in Elgg 3.x/4.x
      return true;
    });
    expect(entities.length).toBeGreaterThan(0);

    const latest = entities[0];
    const titleRows = await getMetadata(latest.guid, 'title');
    const titleValue = titleRows[0]?.value;
    // Either the most recent entity is ours, or at least one with this title exists
    if (titleValue === uniqueTitle) {
      expect(titleValue).toBe(uniqueTitle);

      const street = await getMetadata(latest.guid, 'street_address');
      expect(street[0]?.value).toBe('100 Test Rd');
    } else {
      // Locate by scanning metadata for our unique title
      const found = await Promise.all(
        entities.slice(0, 5).map(async (e: any) => {
          const t = await getMetadata(e.guid, 'title');
          return { guid: e.guid, title: t[0]?.value };
        })
      );
      const match = found.find((f) => f.title === uniqueTitle);
      expect(match, `No hjplace with title "${uniqueTitle}" in latest 5 entities`).toBeTruthy();
    }
  });
});
